version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-task-queue-app1
    ports:
      - "3001:3000"
    depends_on:
      - redis

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-task-queue-app2
    ports:
      - "3002:3000"
    depends_on:
      - redis
